<span style = "color: #82C8E5;"> _Installed Numpy in my ML_DM environment; the env with the only python version of 3.10_ </span>

In [78]:
import sys
print(sys.executable)

c:\Users\kojus\anaconda3\envs\ML_DM\python.exe


In [2]:
import numpy as np

<span style ="color: #87ceeb;"> ___Tasks___ </span>

- Installing numpy via pip, Create a basic 1-D array, Index elements of an array, Use functions np.zeros(), np.ones(), np.empty() to initialise some basic arrays,Shape and Size of numpy arrays, ndim,size, shape, Array reshaping,
 Basic Array Operations, Broadcasting
Working with Mathematical Formulas

In [3]:
# An array is like an arbitrary store for storinga nd retrieving data

np.array([1,2,3,4,5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
[1,2,3,4,5,6,7,8]

[1, 2, 3, 4, 5, 6, 7, 8]

<span style="color: #87ceeb;"> _Comments_: </span>

From my [research](https://numpy.org/doc/stable/user/absolute_beginners.html) and [understanding](https://chat.deepseek.com/a/chat/s/c42f3d4e-7444-46f6-9ea2-6f4af96c71be), the difference between a Python and Numpy array:

- I understand that Numpy is faster in its output operation than a python mathematical list
- Numpy allows for easier mathaematical operation per item in the array using slicing- where for python same would have top be done using for loop
- Numpy works more effiiently on vectorization- which will support the basis of Neural Network
- Numpy arrays can be access with ___Indexing___  a[1], ___slicing___ [2:3], [2:6,2],[:8,2], [::-1] (reverse) ,and ___Iterating___ _{for i in a: print(i**3/2)}_ , ***where Python solely relies on iteration***
- Numpy is faster in its output than Python

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a[0:2]
#start at row 0  and end at row 2 (whuch does not include row 2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a[2:0]

#I realize that when the stop number is less than the start; an enpty array will always be returned
#So, to gte what is needed, it can be ordered such that the start is smaller but the skip will be in reverse

array([], shape=(0, 4), dtype=int64)

In [8]:
a[0:3:-1]

#the reason this is returning an emplty array is because
# from a reverse pov, the start number is still small.

array([], shape=(0, 4), dtype=int64)

In [9]:
a[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[3:0:-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [11]:
a[3::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [12]:
# to get elements [123 through till 9-11]
a[0:3, 0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [13]:
# to get elements [123 through till 9-11] in reverse order
a[3:0:-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [14]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# to fetch the element 7
a[1, 2]

np.int64(7)

In [16]:
a.ndim 

# Meaning that this is a family lits only containg 1 list; which makes it 2

2

In [17]:
a.shape

# number of rows, number of coloumns

(3, 4)

In [18]:
a.size

# no.of rows * no. of col

12

In [19]:
a.dtype

dtype('int64')

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones([10, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [23]:
arr = np.empty(5)
for i in range(5):
    arr[i] = i * 2  # All elements are set before use
arr 

array([0., 2., 4., 6., 8.])

In [24]:
arr = np.zeros(5)
for i in range(5):
    arr[i] = i * 2  # All elements are set before use
arr 

array([0., 2., 4., 6., 8.])

The difference between `empty` and `zeros` is that empty holds space in array to input any value of choice than zeros or ones.

In [25]:
arra = np.empty(20)

for i in range(20):
    arra[i] = i**2

arra

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.,
       121., 144., 169., 196., 225., 256., 289., 324., 361.])

In [26]:
arra = np.empty((4, 5))

for i in range(4):
    for j in range(5):
        arra[i, j] = (i * 5 + j) ** 2

arra

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.]])

In [27]:
np.arange(10,100,10)

#start from 10, stop at 100 and skip by 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
#np.arange([[10:100:10], [20:200:10]])

#start from 10, stop at 100 and skip by 10


In [29]:
# Correct way to create a 2D array with two different ranges as rows
row1 = np.arange(10, 100, 10)
row2 = np.arange(20, 110, 10)
array_2d = np.vstack([row1, row2])
array_2d

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90],
       [ 20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [30]:
row1.shape

(9,)

In [31]:
row2.shape

(9,)

In [32]:
row1.ndim

1

In [33]:
row2.ndim

1

In [34]:
row1 = np.arange(1, 100, 5)
row2 = np.arange(1, 100, 5)
row3 = np.arange(1, 100, 5)

array_3d = np.vstack([row1, row2, row3])

array_3d

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96]])

In [35]:
row1 = np.arange(1, 6)
row2 = np.arange(6, 11)
row3 = np.arange(11, 16)
row4 = np.arange(16, 21)
row5 = np.arange(21, 26)
array_2d = np.vstack([row1, row2, row3, row4, row5])
print(array_2d.shape)  # (5, 5)
array_2d

(5, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
np.linspace(10, 100, 20)

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

In [37]:
np.arange(10,100,20)

array([10, 30, 50, 70, 90])

<span style = "color: #87ceeb;"> _Comments_: </span>
- vstack helps combine arrays

- which comes in handy when an already created array needs to be updated (to add new rows)...maybe not updating the array
- The dfference between `arange` and `linspace` is that the former has a __skip number__ which determines the pace at which the next number orderly, while the later has a __num__ = _total_desired_value_to_be_returned_. This solely states the total number of number to be returned.

<span style = "color: #87ceeb;"> Array Attributes </span>:
- .ndim
- .shape
- .size


<span style="color: #87ceeb ;"> Creating Basic Arrays </span>:
- np.zeros()
- np.ones()
- np.arange()
- np.linspace()
- np.random.random()

<span style="color: #87ceeb ;"> Mathematical Operations </span>:
- .sum()
- .max()
- .min()

<span style="color: #87ceeb ;"> Modifying Arrays </span>:
- np.vstack
- np.concatenate
- np.flip()
- np.reshape
- np.sort()

<span style="color: #87ceeb ;"> Modifying Dimension </span>:
- np.newaxis
- np.expand_dims
- np.flatten()
- np.ravel()

In [38]:
a = np.array([8,7,90,20,1,0.5])

a

array([ 8. ,  7. , 90. , 20. ,  1. ,  0.5])

In [39]:
np.sort(a)

array([ 0.5,  1. ,  7. ,  8. , 20. , 90. ])

other sort types:

- argsort
- lexsort
- searchsorted
- partition

In [40]:
a = np.array([1,2,3,4,5])
b = np.arange(0,5)
c = np.linspace(10,50,5)

np.concatenate([[a,b,c]])

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [10., 20., 30., 40., 50.]])

In [41]:
np.concatenate((a,b,c))

array([ 1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4., 10., 20., 30.,
       40., 50.])

In [42]:
np.vstack([a,b,c])

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [10., 20., 30., 40., 50.]])

In [43]:
np.vstack((a,b,c))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [10., 20., 30., 40., 50.]])

<span style ="color: #87ceeb;"> Comments </span>
- From the above, `concatenate` __horozontally merges the rows as one single row__, while `vstack` __stacks them on each other vertically__.

In [44]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

z =np.concatenate((x, y), axis=0)
z

#So, axis=0 means "add more rows." Both arrays must have the same number of column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.size(z)

6

In [46]:
np.reshape(z, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.reshape(z, (6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a

array([1, 2, 3, 4, 5, 6])

In [49]:
a3 = a[np.newaxis,:]
a3

array([[1, 2, 3, 4, 5, 6]])

In [50]:
a4 = a[:, np.newaxis]
a4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [52]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [53]:

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [54]:
print (a==5)

[[False False False False]
 [ True False False False]
 [False False False False]]


In [55]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [56]:
print(a[(a<=10) & (a>=3)])

[ 3  4  5  6  7  8  9 10]


In [57]:
#array allows broadcast

np.array([1,2,3.5,4]) *10

array([10., 20., 35., 40.])

In [58]:
a.sum()

#sums up an entire array

np.int64(78)

In [59]:
a.max()

np.int64(12)

In [60]:
a.min()

np.int64(1)

In [61]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [64]:
a.shape

(3, 4)

In [65]:
np.reshape(a, (6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [66]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [67]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
np.flip(a)

# reverses given array

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [69]:
a.ndim

2

In [70]:
a.shape

(3, 4)

In [71]:
a = a[np.newaxis, np.newaxis]

In [72]:
a.ndim

4

In [73]:
a

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [74]:
b = a.flatten()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
b.ndim

1

In [76]:
a.ndim

4

In [77]:
#with ravel, the items in original data is also altered
# the ndim will be different- but the element become alike
c=a.ravel()
c[0]=20

print(c)
print(c.ndim)

print(a)
print(a.ndim)

[20  2  3  4  5  6  7  8  9 10 11 12]
1
[[[[20  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]
4
